
from service.resource_manager import get_app_config

LANG_DISPLAY_NAMES = {
    "en": {
        "en": "English",
        "zh-hans": "Chinese (Simplified)",
        "zh-hant": "Chinese (Traditional)",
        "zh": "Chinese",
        "ja": "Japanese",
        "ko": "Korean",
        "fr": "French",
        "de": "German",
        "es": "Spanish",
        "it": "Italian",
        "ru": "Russian",
        "pt": "Portuguese",
        "ar": "Arabic",
        "hi": "Hindi",
        "id": "Indonesian",
        "tr": "Turkish",
        "vi": "Vietnamese",
        "pl": "Polish",
        "nl": "Dutch",
        "th": "Thai",
        "sv": "Swedish",
        "el": "Greek",
        "hu": "Hungarian",
        "cs": "Czech",
        "ro": "Romanian",
        "fi": "Finnish",
        "da": "Danish",
        "no": "Norwegian",
    },
    "zh_CN": {
        "en": "英语",
        "zh-hans": "中文(简体)",
        "zh-hant": "中文(繁體)",
        "zh": "中文",
        "ja": "日语",
        "ko": "韩语",
        "fr": "法语",
        "de": "德语",
        "es": "西班牙语",
        "it": "意大利语",
        "ru": "俄语",
        "pt": "葡萄牙语",
        "ar": "阿拉伯语",
        "hi": "印地语",
        "id": "印尼语",
        "tr": "土耳其语",
        "vi": "越南语",
        "pl": "波兰语",
        "nl": "荷兰语",
        "th": "泰语",
        "sv": "瑞典语",
        "el": "希腊语",
        "hu": "匈牙利语",
        "cs": "捷克语",
        "ro": "罗马尼亚语",
        "fi": "芬兰语",
        "da": "丹麦语",
        "no": "挪威语",
    },
    "zh_TW": {
        "en": "英語",
        "zh-hans": "中文(簡體)",
        "zh-hant": "中文(繁體)",
        "zh": "中文",
        "ja": "日語",
        "ko": "韓語",
        "fr": "法語",
        "de": "德語",
        "es": "西班牙語",
        "it": "義大利語",
        "ru": "俄語",
        "pt": "葡萄牙語",
        "ar": "阿拉伯語",
        "hi": "印地語",
        "id": "印尼語",
        "tr": "土耳其語",
        "vi": "越南語",
        "pl": "波蘭語",
        "nl": "荷蘭語",
        "th": "泰語",
        "sv": "瑞典語",
        "el": "希臘語",
        "hu": "匈牙利語",
        "cs": "捷克語",
        "ro": "羅馬尼亞語",
        "fi": "芬蘭語",
        "da": "丹麥語",
        "no": "挪威語",
    },
    "ja": {
        "en": "英語",
        "zh-hans": "中国語(簡体字)",
        "zh-hant": "中国語(繁体字)",
        "zh": "中国語",
        "ja": "日本語",
        "ko": "韓国語",
        "fr": "フランス語",
        "de": "ドイツ語",
        "es": "スペイン語",
        "it": "イタリア語",
        "ru": "ロシア語",
        "pt": "ポルトガル語",
        "ar": "アラビア語",
        "hi": "ヒンディー語",
        "id": "インドネシア語",
        "tr": "トルコ語",
        "vi": "ベトナム語",
        "pl": "ポーランド語",
        "nl": "オランダ語",
        "th": "タイ語",
        "sv": "スウェーデン語",
        "el": "ギリシャ語",
        "hu": "ハンガリー語",
        "cs": "チェコ語",
        "ro": "ルーマニア語",
        "fi": "フィンランド語",
        "da": "デンマーク語",
        "no": "ノルウェー語",
    },
    "ko": {
        "en": "영어",
        "zh-hans": "중국어(간체)",
        "zh-hant": "중국어(번체)",
        "zh": "중국어",
        "ja": "일본어",
        "ko": "한국어",
        "fr": "프랑스어",
        "de": "독일어",
        "es": "스페인어",
        "it": "이탈리아어",
        "ru": "러시아어",
        "pt": "포르투갈어",
        "ar": "아랍어",
        "hi": "힌디어",
        "id": "인도네시아어",
        "tr": "터키어",
        "vi": "베트남어",
        "pl": "폴란드어",
        "nl": "네덜란드어",
        "th": "태국어",
        "sv": "스웨덴어",
        "el": "그리스어",
        "hu": "헝가리어",
        "cs": "체코어",
        "ro": "루마니아어",
        "fi": "핀란드어",
        "da": "덴마크어",
        "no": "노르웨이어",
    },
    "vi": {
        "en": "Tiếng Anh",
        "zh-hans": "Tiếng Trung (Giản thể)",
        "zh-hant": "Tiếng Trung (Phồn thể)",
        "zh": "Tiếng Trung",
        "ja": "Tiếng Nhật",
        "ko": "Tiếng Hàn",
        "fr": "Tiếng Pháp",
        "de": "Tiếng Đức",
        "es": "Tiếng Tây Ban Nha",
        "it": "Tiếng Ý",
        "ru": "Tiếng Nga",
        "pt": "Tiếng Bồ Đào Nha",
        "ar": "Tiếng Ả Rập",
        "hi": "Tiếng Hindi",
        "id": "Tiếng Indonesia",
        "tr": "Tiếng Thổ Nhĩ Kỳ",
        "vi": "Tiếng Việt",
        "pl": "Tiếng Ba Lan",
        "nl": "Tiếng Hà Lan",
        "th": "Tiếng Thái",
        "sv": "Tiếng Thụy Điển",
        "el": "Tiếng Hy Lạp",
        "hu": "Tiếng Hungary",
        "cs": "Tiếng Séc",
        "ro": "Tiếng Romania",
        "fi": "Tiếng Phần Lan",
        "da": "Tiếng Đan Mạch",
        "no": "Tiếng Na Uy",
    }
}

def get_locale_string(key, *args):
    return key.format(*args)

def get_available_display_languages():
    default_lang:str=get_app_config().language
    return LANG_DISPLAY_NAMES.get(default_lang, LANG_DISPLAY_NAMES['en'])

def find_lang_by_display_name(lang:str) ->str:
    return get_available_display_languages().get(lang.lower(), lang)