

# localization.py

LANGUAGES = {
    "en": "English",
    "zh-Hans": "简体中文 (Simplified)",
    "zh-Hant": "繁體中文 (Traditional)",
    "ja": "日本語 (Japanese)",
    "ko": "한국어 (Korean)",
    "vi": "Tiếng Việt (Vietnamese)"
}

# Moved from anki_generator.py and internationalized
LANG_DISPLAY_NAMES = {
    "en": {
        "en": "English",
        "zh-hans": "Chinese (Simplified)",
        "zh-hant": "Chinese (Traditional)",
        "ja": "Japanese",
        "ko": "Korean",
        "fr": "French",
        "de": "German",
        "es": "Spanish",
        "it": "Italian",
        "ru": "Russian",
        "pt": "Portuguese",
        "ar": "Arabic",
        "hi": "Hindi",
        "id": "Indonesian",
        "tr": "Turkish",
        "vi": "Vietnamese",
        "pl": "Polish",
        "nl": "Dutch",
        "th": "Thai",
        "sv": "Swedish",
        "el": "Greek",
        "hu": "Hungarian",
        "cs": "Czech",
        "ro": "Romanian",
        "fi": "Finnish",
        "da": "Danish",
        "no": "Norwegian",
    },
    "zh-Hans": {
        "en": "英语",
        "zh-hans": "中文(简体)",
        "zh-hant": "中文(繁體)",
        "ja": "日语",
        "ko": "韩语",
        "fr": "法语",
        "de": "德语",
        "es": "西班牙语",
        "it": "意大利语",
        "ru": "俄语",
        "pt": "葡萄牙语",
        "ar": "阿拉伯语",
        "hi": "印地语",
        "id": "印尼语",
        "tr": "土耳其语",
        "vi": "越南语",
        "pl": "波兰语",
        "nl": "荷兰语",
        "th": "泰语",
        "sv": "瑞典语",
        "el": "希腊语",
        "hu": "匈牙利语",
        "cs": "捷克语",
        "ro": "罗马尼亚语",
        "fi": "芬兰语",
        "da": "丹麦语",
        "no": "挪威语",
    },
    "zh-Hant": {
        "en": "英語",
        "zh-hans": "中文(簡體)",
        "zh-hant": "中文(繁體)",
        "ja": "日語",
        "ko": "韓語",
        "fr": "法語",
        "de": "德語",
        "es": "西班牙語",
        "it": "義大利語",
        "ru": "俄語",
        "pt": "葡萄牙語",
        "ar": "阿拉伯語",
        "hi": "印地語",
        "id": "印尼語",
        "tr": "土耳其語",
        "vi": "越南語",
        "pl": "波蘭語",
        "nl": "荷蘭語",
        "th": "泰語",
        "sv": "瑞典語",
        "el": "希臘語",
        "hu": "匈牙利語",
        "cs": "捷克語",
        "ro": "羅馬尼亞語",
        "fi": "芬蘭語",
        "da": "丹麥語",
        "no": "挪威語",
    },
    "ja": {
        "en": "英語",
        "zh-hans": "中国語(簡体字)",
        "zh-hant": "中国語(繁体字)",
        "ja": "日本語",
        "ko": "韓国語",
        "fr": "フランス語",
        "de": "ドイツ語",
        "es": "スペイン語",
        "it": "イタリア語",
        "ru": "ロシア語",
        "pt": "ポルトガル語",
        "ar": "アラビア語",
        "hi": "ヒンディー語",
        "id": "インドネシア語",
        "tr": "トルコ語",
        "vi": "ベトナム語",
        "pl": "ポーランド語",
        "nl": "オランダ語",
        "th": "タイ語",
        "sv": "スウェーデン語",
        "el": "ギリシャ語",
        "hu": "ハンガリー語",
        "cs": "チェコ語",
        "ro": "ルーマニア語",
        "fi": "フィンランド語",
        "da": "デンマーク語",
        "no": "ノルウェー語",
    },
    "ko": {
        "en": "영어",
        "zh-hans": "중국어(간체)",
        "zh-hant": "중국어(번체)",
        "ja": "일본어",
        "ko": "한국어",
        "fr": "프랑스어",
        "de": "독일어",
        "es": "스페인어",
        "it": "이탈리아어",
        "ru": "러시아어",
        "pt": "포르투갈어",
        "ar": "아랍어",
        "hi": "힌디어",
        "id": "인도네시아어",
        "tr": "터키어",
        "vi": "베트남어",
        "pl": "폴란드어",
        "nl": "네덜란드어",
        "th": "태국어",
        "sv": "스웨덴어",
        "el": "그리스어",
        "hu": "헝가리어",
        "cs": "체코어",
        "ro": "루마니아어",
        "fi": "핀란드어",
        "da": "덴마크어",
        "no": "노르웨이어",
    },
    "vi": {
        "en": "Tiếng Anh",
        "zh-hans": "Tiếng Trung (Giản thể)",
        "zh-hant": "Tiếng Trung (Phồn thể)",
        "ja": "Tiếng Nhật",
        "ko": "Tiếng Hàn",
        "fr": "Tiếng Pháp",
        "de": "Tiếng Đức",
        "es": "Tiếng Tây Ban Nha",
        "it": "Tiếng Ý",
        "ru": "Tiếng Nga",
        "pt": "Tiếng Bồ Đào Nha",
        "ar": "Tiếng Ả Rập",
        "hi": "Tiếng Hindi",
        "id": "Tiếng Indonesia",
        "tr": "Tiếng Thổ Nhĩ Kỳ",
        "vi": "Tiếng Việt",
        "pl": "Tiếng Ba Lan",
        "nl": "Tiếng Hà Lan",
        "th": "Tiếng Thái",
        "sv": "Tiếng Thụy Điển",
        "el": "Tiếng Hy Lạp",
        "hu": "Tiếng Hungary",
        "cs": "Tiếng Séc",
        "ro": "Tiếng Romania",
        "fi": "Tiếng Phần Lan",
        "da": "Tiếng Đan Mạch",
        "no": "Tiếng Na Uy",
    }
}

STRINGS = {
    "en": {
        "app_title": "Anki Package Generator",
        "CSV_generate": "Generate Cards from CSV",
        "tab_download": "Download Audio/Video and Subtitles",
        "tab_generate": "Generate Anki Package",
        "tab_config": "Configuration",
        "label_progress": "Progress:",
        "label_log": "Log",
        "log_app_started": "Application started",
        "label_video_url": "Video URL:",
        "button_query_language": "Query Languages",
        "label_download_dir": "Download Directory:",
        "button_browse": "Browse...",
        "label_av_format": "Audio/Video Format:",
        "label_front_sub_lang": "Front Subtitle Language:",
        "label_back_sub_lang": "Back Subtitle Language:",
        "check_download_only_subs": "Download subtitles only",
        "select_display_language": "Select Display Language:",
        "button_start_download": "Start Download",
        "label_media_file": "Media File (Optional):",
        "label_front_sub_file": "Front Subtitle File:",
        "label_back_sub_file": "Back Subtitle File:",
        "label_output_dir": "Output Directory:",
        "label_anki_package_name": "Anki Package Name:",
        "label_tts_engine": "TTS Engine:",
        "radio_no_tts": "Do not generate MP3",
        "label_slow_speech": "Slow Speech (gTTS):",
        "check_slow_front": "Slow Front",
        "check_slow_back": "Slow Back",
        "label_subtitle_cleanup": "Subtitle Cleanup:",
        "check_remove_non_dialogue": "Remove non-dialogue like [Music], (Applause)",
        "label_ruby_char_options": "Ruby Character Options:",
        "check_add_ruby_front": "Add to Front",
        "check_add_ruby_back": "Add to Back",
        "label_post_processing": "Post-processing:",
        "check_cleanup_mp3": "Clean up .mp3 files",
        "check_cleanup_csv": "Clean up .csv files",
        "label_timeline_offset": "Timeline Offset (ms):",
        "label_subtitle_time_range": "Subtitle Time Range:",
        "label_start_time": "Start (HH:MM:SS):",
        "label_end_time": "End (HH:MM:SS):",
        "label_empty_for_end": "(empty for end)",
        "label_subtitle_merge": "Subtitle Merging:",
        "tooltip_merge_warning": "Use with caution: Merges subtitle lines that are very close in time.\nThis may cause misalignment between front and back subtitles or inaccurate audio timing.",
        "check_merge_subtitles": "Merge nearby subtitle lines",
        "label_max_merge_gap": "Max Gap (ms):",
        "label_file_handling": "File Handling:",
        "check_overwrite_anki": "Overwrite existing Anki package",
        "button_preview": "Preview First 5 Cards",
        "button_generate": "Generate Anki Package",
        "label_default_front_lang": "Default Front Subtitle Language:",
        "label_default_back_lang": "Default Back Subtitle Language:",
        "label_anki_template_style": "Anki Templates and Styling:",
        "tab_front_template": "Front Template",
        "tab_back_template": "Back Template",
        "tab_stylesheet": "Stylesheet",
        "tab_preview_html_template": "Preview HTML Template",
        "button_restore_config": "Restore Defaults",
        "button_save_config": "Save Configuration",
        "log_config_updated": "Configuration updated in UI",
        "log_config_restored": "Configuration has been restored",
        "log_config_saved": "Configuration has been saved",
        "error_saving_config": "Error saving configuration: {}",
        "log_url_from_clipboard": "Detected URL from clipboard: {}",
        "error_checking_clipboard": "Error checking clipboard: {}",
        "error_enter_video_url": "Please enter a video URL",
        "error_enter_valid_url": "Please enter a valid URL",
        "log_querying_video_info": "Querying video info: {}",
        "error_querying_video_info": "Error querying video info: {}",
        "log_query_complete": "Query complete. Found {} formats and {} subtitles.",
        "error_playlist_not_supported": "Playlist URLs are not supported. Please provide a single video URL.",
        "filetype_media_files": "Media Files",
        "log_auto_set_output_dir": "Automatically set output directory to: {}",
        "log_auto_set_package_name": "Automatically set Anki package name to: {}",
        "filetype_subtitle_files": "Subtitle Files",
        "log_auto_set_output_dir_from_sub": "Automatically set output directory based on subtitle file: {}",
        "log_trying_auto_match_subs": "Trying to auto-match subtitles for media file: {}",
        "log_no_default_lang_for_match": "Default subtitle languages not set in config, skipping auto-match.",
        "log_auto_matched_front_sub": "Auto-matched front subtitle file ({}): {}",
        "log_auto_matched_back_sub": "Auto-matched back subtitle file ({}): {}",
        "error_select_download_dir": "Please select a download directory",
        "log_created_download_dir": "Created download directory: {}",
        "error_creating_download_dir": "Error creating download directory: {}",
        "error_select_av_format": "Please select an audio/video format",
        "error_select_sub_lang": "Please select subtitle languages",
        "log_processing_started": "Starting to process: {}",
        "log_download_dir": "Download directory: {}",
        "log_front_sub_lang": "Front subtitle language: {}",
        "log_back_sub_lang": "Back subtitle language: {}",
        "log_skip_media_download": "Skipping media file download as requested.",
        "log_selected_format": "Selected format: {}",
        "log_starting_media_download": "Starting to download media file and subtitles...",
        "log_media_download_complete": "Media file download complete: {}",
        "warning_media_file_not_found": "Could not find the downloaded media file.",
        "log_skipped_media_download": "Skipped media file download.",
        "log_front_sub_download_complete": "Front subtitle file download complete: {}",
        "warning_front_sub_not_found": "Could not find front subtitle file ({}).",
        "log_back_sub_download_complete": "Back subtitle file download complete: {}",
        "warning_back_sub_not_found": "Could not find back subtitle file ({}).",
        "title_download_complete": "Download Complete",
        "log_download_finished_processing": "Download finished, processing...",
        "error_downloading": "Error during download: {}",
        "log_download_complete_log": "Download complete",
        "prompt_autofill": "Download complete. Autofill file paths to the 'Generate Anki Package' tab?",
        "error_detecting_lang": "Error detecting language: {}",
        "error_parsing_srt": "Error parsing subtitle file: {}",
        "error_invalid_time_format": "Invalid time format: {}",
        "log_applying_start_time": "Applying start time: {} ({}ms)",
        "log_applying_end_time": "Applying end time: {} ({}ms)",
        "warning_edge_tts_no_slow": "edge-tts does not support slow speech, generating at normal speed.",
        "error_unknown_tts_engine": "Unknown TTS engine: {}",
        "error_generating_tts": "Error generating TTS with '{}': {}",
        "warning_tts_fallback": "TTS engine '{}' failed. Trying fallback engine '{}'...",
        "log_tts_fallback_success": "Fallback TTS engine '{}' succeeded.",
        "error_extracting_audio": "Error extracting audio segment: {}",
        "warning_add_furigana": "Error adding furigana: '{}'. Error: {}",
        "warning_add_pinyin": "Error adding pinyin: '{}'. Error: {}",
        "warning_add_romanization_ko": "Error adding Korean romanization: '{}'. Error: {}",
        "error_preview_need_subs": "Please select front and back subtitle files for preview.",
        "error_preview_need_output_dir": "Please select an output directory to save the preview file.",
        "log_preview_generating": "Generating preview...",
        "log_merging_front_subs": "Merging front subtitles, max gap: {}ms",
        "log_merging_back_subs": "Merging back subtitles, max gap: {}ms",
        "error_preview_no_subs": "Failed to parse subtitle files or no subtitles in time range, cannot preview.",
        "error_init_pykakasi": "Failed to initialize pykakasi: {}",
        "warning_no_subs_for_preview": "Not enough subtitle data to generate a preview.",
        "log_processing_preview_cards": "Processing first {} cards for preview...",
        "log_preview_opened": "Preview opened in browser. File saved at: {}",
        "error_generating_preview": "Error generating preview: {}",
        "preview_audio_placeholder_front": "[Front audio will be here]",
        "preview_audio_placeholder_back": "[Back audio will be here]",
        "preview_card_title": "Card {}",
        "preview_card_front": "Front",
        "preview_card_back": "Back",
        "error_need_front_sub": "Please select a front subtitle file",
        "error_need_back_sub": "Please select a back subtitle file",
        "error_need_csv_file": "Please select a CSV file",
        "error_need_output_dir": "Please select an output directory",
        "error_need_package_name": "Please enter an Anki package name",
        "error_invalid_offset": "Timeline offset must be a valid integer.",
        "log_anki_generating": "Generating Anki package...",
        "log_timeline_offset": "Applying timeline offset: {} ms",
        "error_anki_pkg_exists": "Anki package '{}' already exists. Please check 'Overwrite existing Anki package' or change the package name.",
        "log_loading_media": "Loading media file into memory: {}",
        "log_media_loaded": "Media file loaded.",
        "error_loading_media": "Failed to load media file: {}",
        "error_parsing_subs_or_empty": "Failed to parse subtitle files or no subtitles in time range",
        "log_detected_front_lang": "Detected front subtitle language: {}",
        "log_detected_back_lang": "Detected back subtitle language: {}",
        "log_ja_detected_init_kakasi": "Japanese subtitle detected, initializing ruby character tool...",
        "log_kakasi_initialized": "Ruby character tool initialized.",
        "error_init_kakasi": "Failed to initialize ruby character tool (pykakasi): {}",
        "log_zh_detected_add_pinyin": "Chinese subtitle detected, will add Pinyin.",
        "log_ko_detected_add_romanization": "Korean subtitle detected, will add Romanization.",
        "log_generation_progress": "Generation progress: {:.1f}%",
        "warning_extract_audio_failed_tts_fallback": "Failed to extract audio from media file, falling back to TTS for back audio: {}",
        "log_generating_anki_pkg": "Generating Anki package...",
        "anki_model_name": "Bilingual Learning Card",
        "anki_card_name": "Card 1",
        "log_anki_pkg_complete": "Anki package generation complete: {}",
        "error_generating_anki_pkg": "Error generating Anki package: {}",
        "log_cleaning_temp_files": "Cleaning up temporary files...",
        "log_cleaned_mp3": "Temporary .mp3 files cleaned up.",
        "log_cleaned_csv": "Temporary .csv file cleaned up.",
        "error_cleaning_temp_files": "Error cleaning up temporary files: {}",
        "log_config_loaded": "Configuration loaded",
        "error_loading_config": "Error loading configuration: {}",
        "log_deleted_preview_file": "Deleted preview file: {}",
        "error_deleting_preview_file": "Error deleting preview file: {}",
        "label_language": "Language:",
        "label_screenshot_options": "Screenshot Options:",
        "check_add_screenshot": "Add Screenshot",
        "label_screenshot_timestamp": "Timestamp:",
        "label_screenshot_quality": "Quality (1-31):",
        "check_cleanup_jpg": "Clean up .jpg files",
        "check_cleanup_preview_html": "Clean up preview HTML file",
        "log_cleaned_preview_html": "Temporary preview HTML file cleaned up: {}",
        "error_ffmpeg_not_found": "FFmpeg not found. Please ensure FFmpeg is installed and added to your system's PATH.",
        "error_taking_screenshot": "Error taking screenshot: {}",
        "log_screenshot_taken": "Took screenshot at {}s, saved to {}",
        "log_cleaned_jpg": "Temporary .jpg files cleaned up.",
        "preview_screenshot_placeholder": "[Screenshot will be here]",
        "screenshot_time_start": "Start",
        "screenshot_time_middle": "Middle",
        "screenshot_time_end": "End",
        "warning_same_subtitle_language": "Front and back subtitle languages cannot be the same. Back language has been automatically adjusted.",
        "error_no_alternative_language": "No alternative language found for the back subtitle. Please select different languages manually.",
        "error_config_corrupted": "Error: config.json is corrupted. Using default settings.",
        "config_saved_restart": "Configuration saved. Please restart the application for all changes to take effect.",
        "welcome_title": "Initial Setup",
        "welcome_message": "Welcome! To get started, please select your preferred display language and the default languages for the front and back of your Anki cards.",
        "select_front_lang": "Select Default Front Language:",
        "select_back_lang": "Select Default Back Language:",
        "error_select_both_langs": "Please select both a front and a back language to continue.",
        "error_internal_lang_map": "Internal error: Could not map selected language display names to codes.",
        "button_continue": "Continue",
        "button_cancel": "Cancel",
        "label_help": "Help",
        "check_dont_validate_url": "Don't validate URL",
        "log_url_validation_changed": "URL validation has been {}.",
        "tooltip_dont_validate_url_check": "By default, only single YouTube download links like https://www.youtube.com/watch?v=... are supported. If you want to support more download sites from yt-dlp, you can check this to forcibly disable the URL check.",
        "tooltip_label_media_file": "If this field is empty, it means the corresponding file will not be segmented."
    },
    "zh-Hans": {
        "app_title": "Anki数据包生成器",
        "tab_download": "下载音视频和字幕",
        "CSV_generate": "利用CSV生成卡片",
        "tab_generate": "生成Anki包",
        "tab_csv": "CSV",
        "tab_config": "配置",
        "label_progress": "进度:",
        "label_log": "日志",
        "log_app_started": "应用程序已启动",
        "label_video_url": "视频URL:",
        "button_query_language": "查询语言",
        "label_download_dir": "下载目录:",
        "button_browse": "浏览...",
        "label_av_format": "音视频格式:",
        "label_front_sub_lang": "正面字幕语言:",
        "label_back_sub_lang": "背面字幕语言:",
        "check_download_only_subs": "仅下载字幕",
        "select_display_language": "选择显示语言:",
        "button_start_download": "开始下载",
        "label_media_file": "媒体文件(可选):",
        "label_front_sub_file": "正面字幕文件:",
        "label_back_sub_file": "背面字幕文件:",
        "label_csv_file": "CSV文件:",
        "label_output_dir": "输出目录:",
        "label_anki_package_name": "Anki包名称:",
        "label_tts_engine": "TTS引擎:",
        "radio_no_tts": "不生成MP3",
        "label_slow_speech": "慢速语音(gTTS):", 
        "check_slow_front": "正面慢速",
        "check_slow_back": "背面慢速",
        "label_subtitle_cleanup": "字幕清理:",
        "check_remove_non_dialogue": "移除 [音乐], (掌声) 等非对话内容",
        "label_ruby_char_options": "注音选项:",
        "check_add_ruby_front": "正面注音",
        "check_add_ruby_back": "背面注音",
        "label_post_processing": "后期处理:",
        "check_cleanup_mp3": "清理 .mp3 文件",
        "check_cleanup_csv": "清理 .csv 文件",
        "label_timeline_offset": "时间轴偏移(ms):",
        "label_subtitle_time_range": "字幕时间段:",
        "label_start_time": "开始 (HH:MM:SS):",
        "label_end_time": "结束 (HH:MM:SS):",
        "label_empty_for_end": "(空为结束)",
        "label_subtitle_merge": "字幕合并:",
        "tooltip_merge_warning": "谨慎使用：开启后，会尝试将时间间隔很近的字幕行合并为一条。\n这可能导致正面和背面字幕无法一一对应，或音频时间轴不精确。",
        "check_merge_subtitles": "合并时间接近的字幕行",
        "label_max_merge_gap": "最大间隔(ms):",
        "label_file_handling": "文件处理:",
        "check_overwrite_anki": "覆盖同名Anki包",
        "button_preview": "预览前5张卡片",
        "button_generate": "生成Anki包",
        "label_default_front_lang": "默认正面字幕语言:",
        "label_default_back_lang": "默认背面字幕语言:",
        "label_anki_template_style": "Anki模板和样式:",
        "tab_front_template": "正面模板",
        "tab_back_template": "背面模板",
        "tab_stylesheet": "样式表",
        "tab_preview_html_template": "预览HTML模板",
        "button_restore_config": "恢复配置",
        "button_save_config": "保存配置",
        "log_config_updated": "配置已更新到界面",
        "log_config_restored": "配置已恢复",
        "log_config_saved": "配置已保存",
        "error_saving_config": "保存配置时出错: {}",
        "log_url_from_clipboard": "已从剪贴板检测到URL: {}",
        "error_checking_clipboard": "检查剪贴板时出错: {}",
        "error_enter_video_url": "请输入视频URL",
        "error_enter_valid_url": "请输入有效的URL",
        "log_querying_video_info": "正在查询视频信息: {}",
        "error_querying_video_info": "查询视频信息时出错: {}",
        "log_query_complete": "查询完成，找到 {} 种格式和 {} 种字幕",
        "error_playlist_not_supported": "不支持播放列表URL。请提供单个视频URL。",
        "filetype_media_files": "媒体文件",
        "filetype_csv_files": "CSV 文件",
        "log_auto_set_output_dir": "已自动设置输出目录为: {}",
        "log_auto_set_package_name": "已自动设置Anki包名称为: {}",
        "filetype_subtitle_files": "字幕文件",
        "log_auto_set_output_dir_from_sub": "已根据字幕文件自动设置输出目录为: {}",
        "log_trying_auto_match_subs": "尝试为媒体文件自动匹配字幕: {}",
        "log_no_default_lang_for_match": "未在配置中设置默认字幕语言，跳过自动匹配。",
        "log_auto_matched_front_sub": "自动匹配到正面字幕文件 ({})",
        "log_auto_matched_back_sub": "自动匹配到背面字幕文件 ({})",
        "error_select_download_dir": "请选择下载目录",
        "log_created_download_dir": "已创建下载目录: {}",
        "error_creating_download_dir": "创建下载目录时出错: {}",
        "error_select_av_format": "请选择音视频格式",
        "error_select_sub_lang": "请选择字幕语言",
        "log_processing_started": "开始处理: {}",
        "log_download_dir": "下载目录: {}",
        "log_front_sub_lang": "正面字幕语言: {}",
        "log_back_sub_lang": "背面字幕语言: {}",
        "log_skip_media_download": "已选择仅下载字幕，将跳过媒体文件下载。",
        "log_selected_format": "选择的格式: {}",
        "log_starting_media_download": "开始下载媒体文件和字幕...",
        "log_media_download_complete": "媒体文件下载完成: {}",
        "warning_media_file_not_found": "未能找到下载的媒体文件。",
        "log_skipped_media_download": "已跳过媒体文件下载。",
        "log_front_sub_download_complete": "正面字幕文件下载完成: {}",
        "warning_front_sub_not_found": "未能找到正面字幕文件 ({}).",
        "log_back_sub_download_complete": "背面字幕文件下载完成: {}",
        "warning_back_sub_not_found": "未能找到背面字幕文件 ({}).",
        "title_download_complete": "下载完成",
        "log_download_finished_processing": "下载完成，正在处理...",
        "error_downloading": "下载时出错: {}",
        "log_download_complete_log": "下载完成",
        "prompt_autofill": "是否将下载的文件自动填充到生成Anki包页面?",
        "error_detecting_lang": "检测语言时出错: {}",
        "error_parsing_srt": "解析字幕文件时出错: {}",
        "error_invalid_time_format": "无效的时间格式: {}",
        "log_applying_start_time": "应用开始时间: {} ({}ms)",
        "log_applying_end_time": "应用结束时间: {} ({}ms)",
        "warning_edge_tts_no_slow": "edge-tts 不支持慢速语音，将以正常速度生成。",
        "error_unknown_tts_engine": "未知的TTS引擎: {}",
        "error_generating_tts": "使用 '{}' 生成TTS时出错: {}",
        "warning_tts_fallback": "TTS引擎 '{}' 失败。正在尝试备用引擎 '{}'...",
        "log_tts_fallback_success": "备用TTS引擎 '{}' 成功。",
        "error_extracting_audio": "提取音频片段时出错: {}",
        "warning_add_furigana": "添加注音时出错: '{}'. Error: {}",
        "warning_add_pinyin": "添加拼音时出错: '{}'. Error: {}",
        "warning_add_romanization_ko": "添加韩语罗马音时出错: '{}'. Error: {}",
        "error_preview_need_subs": "请选择正面和背面字幕文件以进行预览。",
        "error_preview_need_output_dir": "请选择输出目录以保存预览文件。",
        "log_preview_generating": "开始生成预览...",
        "log_merging_front_subs": "正在合并正面字幕，最大间隔: {}ms",
        "log_merging_back_subs": "正在合并背面字幕，最大间隔: {}ms",
        "error_preview_no_subs": "字幕文件解析失败或时间段内无字幕，无法预览。",
        "error_init_pykakasi": "初始化注音工具(pykakasi)失败: {}",
        "warning_no_subs_for_preview": "没有足够的字幕数据来生成预览。",
        "log_processing_preview_cards": "正在处理前 {} 张卡片...",
        "log_preview_opened": "预览已在浏览器中打开。文件保存在: {}",
        "error_generating_preview": "生成预览时出错: {}",
        "preview_audio_placeholder_front": "[正面音频将在此处]",
        "preview_audio_placeholder_back": "[背面音频将在此处]",
        "preview_card_title": "卡片 {}",
        "preview_card_front": "正面",
        "preview_card_back": "背面",
        "error_need_front_sub": "请选择正面字幕文件",
        "error_need_back_sub": "请选择背面字幕文件",
        "error_need_csv_file": "请选择CSV文件",
        "error_need_output_dir": "请选择输出目录",
        "error_need_package_name": "请输入Anki包名称",
        "error_invalid_offset": "时间轴偏移量必须是一个有效的整数。",
        "log_anki_generating": "开始生成Anki包",
        "log_anki_generating_from_csv": "正在从CSV生成Anki包...",
        "log_timeline_offset": "应用时间轴偏移: {} ms",
        "error_anki_pkg_exists": "Anki包 '{}' 已存在。请勾选 '覆盖同名Anki包' 或更改Anki包名称。",
        "log_loading_media": "正在加载媒体文件到内存: {}",
        "log_media_loaded": "媒体文件加载完成。",
        "error_loading_media": "加载媒体文件失败: {}",
        "error_parsing_subs_or_empty": "字幕文件解析失败或时间段内无字幕",
        "log_detected_front_lang": "检测到正面字幕语言: {}",
        "log_detected_back_lang": "检测到背面字幕语言: {}",
        "log_ja_detected_init_kakasi": "检测到日语字幕，正在初始化注音工具...",
        "log_kakasi_initialized": "注音工具初始化完成。",
        "error_init_kakasi": "初始化注音工具(pykakasi)失败: {}",
        "log_zh_detected_add_pinyin": "检测到中文字幕，将添加拼音注音。",
        "log_ko_detected_add_romanization": "检测到韩语字幕，将添加罗马音注音。",
        "log_generation_progress": "生成进度: {:.1f}%",
        "warning_extract_audio_failed_tts_fallback": "从媒体文件提取音频失败，将尝试使用TTS生成背面音频: {}",
        "log_generating_anki_pkg": "正在生成Anki包...",
        "anki_model_name": "双语学习卡片",
        "anki_card_name": "卡片1",
        "log_anki_pkg_complete": "Anki包生成完成: {}",
        "error_generating_anki_pkg": "生成Anki包时出错: {}",
        "log_cleaning_temp_files": "正在清理临时文件...",
        "log_cleaned_mp3": "临时 .mp3 文件已清理。",
        "log_cleaned_csv": "临时 .csv 文件已清理。",
        "error_cleaning_temp_files": "清理临时文件时出错: {}",
        "log_config_loaded": "配置已加载",
        "error_loading_config": "加载配置时出错: {}",
        "log_deleted_preview_file": "已删除预览文件: {}",
        "error_deleting_preview_file": "删除预览文件时出错: {}",
        "label_language": "语言:",
        "label_screenshot_options": "截图选项:",
        "check_add_screenshot": "添加截图",
        "label_screenshot_timestamp": "截图时间点:",
        "label_screenshot_quality": "质量 (1-31):",
        "check_cleanup_jpg": "清理 .jpg 文件",
        "check_cleanup_preview_html": "清理预览HTML文件",
        "log_cleaned_preview_html": "临时预览HTML文件已清理: {}",
        "error_ffmpeg_not_found": "未找到 FFmpeg。请确保已安装 FFmpeg 并将其添加到系统 PATH 中。",
        "error_taking_screenshot": "截图时出错: {}",
        "log_screenshot_taken": "在 {}s 截取屏幕截图，保存至 {}",
        "log_cleaned_jpg": "临时 .jpg 文件已清理。",
        "preview_screenshot_placeholder": "[截图将在此处]",
        "screenshot_time_start": "开始",
        "screenshot_time_middle": "中间",
        "screenshot_time_end": "结尾",
        "warning_same_subtitle_language": "正面和背面字幕语言不能相同。背面语言已自动调整。",
        "error_no_alternative_language": "未找到背面字幕的替代语言。请手动选择不同的语言。",
        "error_config_corrupted": "错误：config.json 文件已损坏。将使用默认设置。",
        "config_saved_restart": "配置已保存。请重启应用程序以使所有更改生效。",
        "welcome_title": "初始设置",
        "welcome_message": "欢迎使用！开始前，请选择您偏好的显示语言以及Anki卡片正面和背面的默认语言。",
        "select_front_lang": "选择默认正面语言：",
        "select_back_lang": "选择默认背面语言：",
        "error_select_both_langs": "请同时选择正面和背面语言以继续。",
        "error_internal_lang_map": "内部错误：无法将所选语言显示名称映射到代码。",
        "button_continue": "继续",
        "button_cancel": "取消",
        "label_help": "帮助",
        "check_dont_validate_url": "不验证URL",
        "log_url_validation_changed": "URL验证已{}",
        "tooltip_dont_validate_url_check": "默认只支持单个youtube下载地址，如 https://www.youtube.com/watch?v=....，如果想支持更多yt-dlp的下载网站，可以将其勾选中，强制取消对URL的检查",
        "tooltip_label_media_file": "如果该项内容为空，则表示不分割相应的文件"
    },
    "zh-Hant": {
        "app_title": "Anki卡片包生成器",
        "tab_download": "下載音訊/視訊和字幕",
        "CSV_generate": "利用CSV產生卡片",
        "tab_generate": "生成Anki卡片包",
        "tab_csv": "CSV",
        "tab_config": "設定",
        "label_progress": "進度:",
        "label_log": "日誌",
        "log_app_started": "應用程式已啟動",
        "label_video_url": "影片URL:",
        "button_query_language": "查詢語言",
        "label_download_dir": "下載目錄:",
        "button_browse": "瀏覽...",
        "label_av_format": "音訊/視訊格式:",
        "label_front_sub_lang": "正面字幕語言:",
        "label_back_sub_lang": "背面字幕語言:",
        "check_download_only_subs": "僅下載字幕",
        "select_display_language": "選擇顯示語言:",
        "button_start_download": "開始下載",
        "label_media_file": "媒體檔案(可選):",
        "label_front_sub_file": "正面字幕檔案:",
        "label_back_sub_file": "背面字幕檔案:",
        "label_csv_file": "CSV檔案:",
        "label_output_dir": "輸出目錄:",
        "label_anki_package_name": "Anki卡片包名稱:",
        "label_tts_engine": "TTS引擎:",
        "radio_no_tts": "不生成MP3",
        "label_slow_speech": "慢速語音(gTTS):", 
        "check_slow_front": "正面慢速",
        "check_slow_back": "背面慢速",
        "label_subtitle_cleanup": "字幕清理:",
        "check_remove_non_dialogue": "移除 [音樂], (掌聲) 等非對話內容",
        "label_ruby_char_options": "注音選項:",
        "check_add_ruby_front": "正面注音",
        "check_add_ruby_back": "背面注音",
        "label_post_processing": "後期處理:",
        "check_cleanup_mp3": "清理 .mp3 檔案",
        "check_cleanup_csv": "清理 .csv 檔案",
        "label_timeline_offset": "時間軸偏移(ms):",
        "label_subtitle_time_range": "字幕時間範圍:",
        "label_start_time": "開始 (HH:MM:SS):",
        "label_end_time": "結束 (HH:MM:SS):",
        "label_empty_for_end": "(留空為結束)",
        "label_subtitle_merge": "字幕合併:",
        "tooltip_merge_warning": "謹慎使用：開啟後，會嘗試將時間間隔很近的字幕行合併為一條。\n這可能導致正面和背面字幕無法一一對應，或音訊時間軸不精確。",
        "check_merge_subtitles": "合併時間接近的字幕行",
        "label_max_merge_gap": "最大間隔(ms):",
        "label_file_handling": "檔案處理:",
        "check_overwrite_anki": "覆蓋同名Anki卡片包",
        "button_preview": "預覽前5張卡片",
        "button_generate": "生成Anki卡片包",
        "label_default_front_lang": "預設正面字幕語言:",
        "label_default_back_lang": "預設背面字幕語言:",
        "label_anki_template_style": "Anki範本和樣式:",
        "tab_front_template": "正面範本",
        "tab_back_template": "背面範本",
        "tab_stylesheet": "樣式表",
        "tab_preview_html_template": "預覽HTML範本",
        "button_restore_config": "恢復預設",
        "button_save_config": "儲存設定",
        "log_config_updated": "設定已更新到介面",
        "log_config_restored": "設定已恢復",
        "log_config_saved": "設定已儲存",
        "error_saving_config": "儲存設定時出錯: {}",
        "log_url_from_clipboard": "已從剪貼簿偵測到URL: {}",
        "error_checking_clipboard": "檢查剪貼簿時出錯: {}",
        "error_enter_video_url": "請輸入影片URL",
        "error_enter_valid_url": "請輸入有效的URL",
        "log_querying_video_info": "正在查詢影片資訊: {}",
        "error_querying_video_info": "查詢影片資訊時出錯: {}",
        "log_query_complete": "查詢完成，找到 {} 種格式和 {} 種字幕",
        "error_playlist_not_supported": "不支援播放清單URL。請提供單一影片URL。",
        "filetype_media_files": "媒體檔案",
        "filetype_csv_files": "CSV 檔案",
        "log_auto_set_output_dir": "已自動設定輸出目錄為: {}",
        "log_auto_set_package_name": "已自動設定Anki卡片包名稱為: {}",
        "filetype_subtitle_files": "字幕檔案",
        "log_auto_set_output_dir_from_sub": "已根據字幕檔案自動設定輸出目錄為: {}",
        "log_trying_auto_match_subs": "嘗試為媒體檔案自動配對字幕: {}",
        "log_no_default_lang_for_match": "未在設定中指定預設字幕語言，跳過自動配對。",
        "log_auto_matched_front_sub": "自動配對到正面字幕檔案 ({})",
        "log_auto_matched_back_sub": "自動配對到背面字幕檔案 ({})",
        "error_select_download_dir": "請選擇下載目錄",
        "log_created_download_dir": "已建立下載目錄: {}",
        "error_creating_download_dir": "建立下載目錄時出錯: {}",
        "error_select_av_format": "請選擇音訊/視訊格式",
        "error_select_sub_lang": "請選擇字幕語言",
        "log_processing_started": "開始處理: {}",
        "log_download_dir": "下載目錄: {}",
        "log_front_sub_lang": "正面字幕語言: {}",
        "log_back_sub_lang": "背面字幕語言: {}",
        "log_skip_media_download": "已選擇僅下載字幕，將跳過媒體檔案下載。",
        "log_selected_format": "選擇的格式: {}",
        "log_starting_media_download": "開始下載媒體檔案和字幕...",
        "log_media_download_complete": "媒體檔案下載完成: {}",
        "warning_media_file_not_found": "未能找到下載的媒體檔案。",
        "log_skipped_media_download": "已跳過媒體檔案下載。",
        "log_front_sub_download_complete": "正面字幕檔案下載完成: {}",
        "warning_front_sub_not_found": "未能找到正面字幕檔案 ({}).",
        "log_back_sub_download_complete": "背面字幕檔案下載完成: {}",
        "warning_back_sub_not_found": "未能找到背面字幕檔案 ({}).",
        "title_download_complete": "下載完成",
        "log_download_finished_processing": "下載完成，正在處理...",
        "error_downloading": "下載時出錯: {}",
        "log_download_complete_log": "下載完成",
        "prompt_autofill": "是否將下載的檔案自動填入到生成Anki卡片包頁面?",
        "error_detecting_lang": "偵測語言時出錯: {}",
        "error_parsing_srt": "解析字幕檔案時出錯: {}",
        "error_invalid_time_format": "無效的時間格式: {}",
        "log_applying_start_time": "套用開始時間: {} ({}ms)",
        "log_applying_end_time": "套用結束時間: {} ({}ms)",
        "warning_edge_tts_no_slow": "edge-tts 不支援慢速語音，將以正常速度生成。",
        "error_unknown_tts_engine": "未知的TTS引擎: {}",
        "error_generating_tts": "使用 '{}' 生成TTS時出錯: {}",
        "warning_tts_fallback": "TTS引擎 '{}' 失敗。正在嘗試備用引擎 '{}'...",
        "log_tts_fallback_success": "備用TTS引擎 '{}' 成功。",
        "error_extracting_audio": "擷取音訊片段時出錯: {}",
        "warning_add_furigana": "添加日文注音時出錯: '{}'. 錯誤: {}",
        "warning_add_pinyin": "添加拼音時出錯: '{}'. 錯誤: {}",
        "warning_add_romanization_ko": "添加韓語羅馬音時出錯: '{}'. 錯誤: {}",
        "error_preview_need_subs": "請選擇正面和背面字幕檔案以進行預覽。",
        "error_preview_need_output_dir": "請選擇輸出目錄以儲存預覽檔案。",
        "log_preview_generating": "開始生成預覽...",
        "log_merging_front_subs": "正在合併正面字幕，最大間隔: {}ms",
        "log_merging_back_subs": "正在合併背面字幕，最大間隔: {}ms",
        "error_preview_no_subs": "字幕檔案解析失敗或時間範圍內無字幕，無法預覽。",
        "error_init_pykakasi": "初始化注音工具(pykakasi)失敗: {}",
        "warning_no_subs_for_preview": "沒有足夠的字幕資料來生成預覽。",
        "log_processing_preview_cards": "正在處理前 {} 張卡片...",
        "log_preview_opened": "預覽已在瀏覽器中開啟。檔案儲存在: {}",
        "error_generating_preview": "生成預覽時出錯: {}",
        "preview_audio_placeholder_front": "[正面音訊將在此處]",
        "preview_audio_placeholder_back": "[背面音訊將在此處]",
        "preview_card_title": "卡片 {}",
        "preview_card_front": "正面",
        "preview_card_back": "背面",
        "error_need_front_sub": "請選擇正面字幕檔案",
        "error_need_back_sub": "請選擇背面字幕檔案",
        "error_need_csv_file": "請選擇CSV檔案",
        "error_need_output_dir": "請選擇輸出目錄",
        "error_need_package_name": "請輸入Anki卡片包名稱",
        "error_invalid_offset": "時間軸偏移量必須是一個有效的整數。",
        "log_anki_generating": "開始生成Anki卡片包",
        "log_anki_generating_from_csv": "正在從CSV生成Anki卡片包...",
        "log_timeline_offset": "套用時間軸偏移: {} ms",
        "error_anki_pkg_exists": "Anki卡片包 '{}' 已存在。請勾選 '覆蓋同名Anki卡片包' 或更改Anki卡片包名稱。",
        "log_loading_media": "正在載入媒體檔案到記憶體: {}",
        "log_media_loaded": "媒體檔案載入完成。",
        "error_loading_media": "載入媒體檔案失敗: {}",
        "error_parsing_subs_or_empty": "字幕檔案解析失敗或時間範圍內無字幕",
        "log_detected_front_lang": "偵測到正面字幕語言: {}",
        "log_detected_back_lang": "偵測到背面字幕語言: {}",
        "log_ja_detected_init_kakasi": "偵測到日語字幕，正在初始化注音工具...",
        "log_kakasi_initialized": "注音工具初始化完成。",
        "error_init_kakasi": "初始化注音工具(pykakasi)失敗: {}",
        "log_zh_detected_add_pinyin": "偵測到中文字幕，將添加拼音注音。",
        "log_ko_detected_add_romanization": "偵測到韓語字幕，將添加羅馬音注音。",
        "log_generation_progress": "生成進度: {:.1f}%",
        "warning_extract_audio_failed_tts_fallback": "從媒體檔案擷取音訊失敗，將嘗試使用TTS生成背面音訊: {}",
        "log_generating_anki_pkg": "正在生成Anki卡片包...",
        "anki_model_name": "雙語學習卡片",
        "anki_card_name": "卡片1",
        "log_anki_pkg_complete": "Anki卡片包生成完成: {}",
        "error_generating_anki_pkg": "生成Anki卡片包時出錯: {}",
        "log_cleaning_temp_files": "正在清理暫存檔案...",
        "log_cleaned_mp3": "暫存 .mp3 檔案已清理。",
        "log_cleaned_csv": "暫存 .csv 檔案已清理。",
        "error_cleaning_temp_files": "清理暫存檔案時出錯: {}",
        "log_config_loaded": "設定已載入",
        "error_loading_config": "載入設定時出錯: {}",
        "log_deleted_preview_file": "已刪除預覽檔案: {}",
        "error_deleting_preview_file": "刪除預覽檔案時出錯: {}",
        "label_language": "語言:",
        "label_screenshot_options": "截圖選項:",
        "check_add_screenshot": "添加截圖",
        "label_screenshot_timestamp": "截圖時間點:",
        "label_screenshot_quality": "質量 (1-31):",
        "check_cleanup_jpg": "清理 .jpg 檔案",
        "check_cleanup_preview_html": "清理預覽HTML檔案",
        "log_cleaned_preview_html": "臨時預覽HTML檔案已清理: {}",
        "error_ffmpeg_not_found": "未找到 FFmpeg。請確保已安裝 FFmpeg 並將其添加到系統 PATH 中。",
        "error_taking_screenshot": "截圖時出錯: {}",
        "log_screenshot_taken": "在 {}s 截取螢幕截圖，儲存至 {}",
        "log_cleaned_jpg": "臨時 .jpg 檔案已清理。",
        "preview_screenshot_placeholder": "[截圖將在此處]",
        "screenshot_time_start": "開始",
        "screenshot_time_middle": "中間",
        "screenshot_time_end": "結尾",
        "warning_same_subtitle_language": "正面和背面字幕語言不能相同。背面語言已自動調整。",
        "error_no_alternative_language": "未找到背面字幕的替代語言。請手動選擇不同的語言。",
        "error_config_corrupted": "錯誤：config.json 檔案已損毀。將使用預設設定。",
        "config_saved_restart": "設定已儲存。請重啟應用程式以使所有變更生效。",
        "welcome_title": "初始設定",
        "welcome_message": "歡迎使用！開始前，請選擇您偏好的顯示語言以及Anki卡片正面和背面的預設語言。",
        "select_front_lang": "選擇預設正面語言：",
        "select_back_lang": "選擇預設背面語言：",
        "error_select_both_langs": "請同時選擇正面和背面語言以繼續。",
        "error_internal_lang_map": "內部錯誤：無法將所選語言顯示名稱對應到代碼。",
        "button_continue": "繼續",
        "button_cancel": "取消",
        "label_help": "幫助",
        "check_dont_validate_url": "不驗證URL",
        "log_url_validation_changed": "URL驗證已{}",
        "tooltip_dont_validate_url_check": "預設僅支援單個YouTube下載地址，如 https://www.youtube.com/watch?v=....，若想支援更多yt-dlp的下載網站，可以將其勾選，強制取消對URL的檢查",
        "tooltip_label_media_file": "如果該項內容為空，則表示不分割相應的檔案"
    },
    "ja": {
        "app_title": "Ankiパッケージジェネレーター",
        "tab_download": "音声/動画と字幕のダウンロード",
        "CSV_generate": "CSVからカードを生成",
        "tab_generate": "Ankiパッケージの生成",
        "tab_csv": "CSV",
        "tab_config": "設定",
        "label_progress": "進捗:",
        "label_log": "ログ",
        "log_app_started": "アプリケーションが起動しました",
        "label_video_url": "動画URL:",
        "button_query_language": "言語のクエリ",
        "label_download_dir": "ダウンロードディレクトリ:",
        "button_browse": "参照...",
        "label_av_format": "音声/動画フォーマット:",
        "label_front_sub_lang": "表面の字幕言語:",
        "label_back_sub_lang": "裏面の字幕言語:",
        "check_download_only_subs": "字幕のみダウンロード",
        "select_display_language": "表示言語を選択:",
        "button_start_download": "ダウンロード開始",
        "label_media_file": "メディアファイル(任意):",
        "label_front_sub_file": "表面の字幕ファイル:",
        "label_back_sub_file": "裏面の字幕ファイル:",
        "label_csv_file": "CSVファイル:",
        "label_output_dir": "出力ディレクトリ:",
        "label_anki_package_name": "Ankiパッケージ名:",
        "label_tts_engine": "TTSエンジン:",
        "label_slow_speech": "低速音声(gTTS):",
        "check_slow_front": "表面を低速",
        "check_slow_back": "裏面を低速",
        "label_subtitle_cleanup": "字幕のクリーンアップ:",
        "check_remove_non_dialogue": "[音楽]、(拍手)などの非会話部分を削除",
        "label_ruby_char_options": "ルビ文字オプション:",
        "check_add_ruby_front": "表面にルビを追加",
        "check_add_ruby_back": "裏面にルビを追加",
        "label_post_processing": "後処理:",
        "check_cleanup_mp3": ".mp3ファイルをクリーンアップ",
        "check_cleanup_csv": ".csvファイルをクリーンアップ",
        "label_timeline_offset": "タイムラインオフセット(ms):",
        "label_subtitle_time_range": "字幕の時間範囲:",
        "label_start_time": "開始 (HH:MM:SS):",
        "label_end_time": "終了 (HH:MM:SS):",
        "label_empty_for_end": "(空で最後まで)",
        "label_subtitle_merge": "字幕のマージ:",
        "tooltip_merge_warning": "注意して使用してください：有効にすると、時間的に非常に近い字幕行がマージされます。\nこれにより、表面と裏面の字幕がずれたり、音声のタイミングが不正確になる可能性があります。",
        "check_merge_subtitles": "近くの字幕行をマージ",
        "label_max_merge_gap": "最大ギャップ(ms):",
        "label_file_handling": "ファイル処理:",
        "check_overwrite_anki": "既存のAnkiパッケージを上書き",
        "button_preview": "最初の5枚のカードをプレビュー",
        "button_generate": "Ankiパッケージを生成",
        "label_default_front_lang": "デフォルトの表面字幕言語:",
        "label_default_back_lang": "デフォルトの裏面字幕言語:",
        "label_anki_template_style": "Ankiのテンプレートとスタイル:",
        "tab_front_template": "表面テンプレート",
        "tab_back_template": "裏面テンプレート",
        "tab_stylesheet": "スタイルシート",
        "tab_preview_html_template": "プレビューHTMLテンプレート",
        "button_restore_config": "デフォルトに戻す",
        "button_save_config": "設定を保存",
        "log_config_updated": "設定がUIに更新されました",
        "log_config_restored": "設定が復元されました",
        "log_config_saved": "設定が保存されました",
        "error_saving_config": "設定の保存中にエラーが発生しました: {}",
        "log_url_from_clipboard": "クリップボードからURLを検出しました: {}",
        "error_checking_clipboard": "クリップボードの確認中にエラーが発生しました: {}",
        "error_enter_video_url": "動画URLを入力してください",
        "error_enter_valid_url": "有効なURLを入力してください",
        "log_querying_video_info": "動画情報をクエリしています: {}",
        "error_querying_video_info": "動画情報のクエリ中にエラーが発生しました: {}",
        "log_query_complete": "クエリ完了。{}個のフォーマットと{}個の字幕が見つかりました。",
        "error_playlist_not_supported": "再生リストのURLはサポートされていません。個別の動画URLを入力してください。",
        "filetype_media_files": "メディアファイル",
        "filetype_csv_files": "CSVファイル",
        "log_auto_set_output_dir": "出力ディレクトリを自動的に設定しました: {}",
        "log_auto_set_package_name": "Ankiパッケージ名を自動的に設定しました: {}",
        "filetype_subtitle_files": "字幕ファイル",
        "log_auto_set_output_dir_from_sub": "字幕ファイルに基づいて出力ディレクトリを自動的に設定しました: {}",
        "log_trying_auto_match_subs": "メディアファイルの字幕を自動的に照合しようとしています: {}",
        "log_no_default_lang_for_match": "設定でデフォルトの字幕言語が設定されていないため、自動照合をスキップします。",
        "log_auto_matched_front_sub": "表面の字幕ファイルを自動照合しました ({}): {}",
        "log_auto_matched_back_sub": "裏面の字幕ファイルを自動照合しました ({}): {}",
        "error_select_download_dir": "ダウンロードディレクトリを選択してください",
        "log_created_download_dir": "ダウンロードディレクトリを作成しました: {}",
        "error_creating_download_dir": "ダウンロードディレクトリの作成中にエラーが発生しました: {}",
        "error_select_av_format": "音声/動画フォーマットを選択してください",
        "error_select_sub_lang": "字幕言語を選択してください",
        "log_processing_started": "処理を開始しています: {}",
        "log_download_dir": "ダウンロードディレクトリ: {}",
        "log_front_sub_lang": "表面の字幕言語: {}",
        "log_back_sub_lang": "裏面の字幕言語: {}",
        "log_skip_media_download": "要求通りメディアファイルのダウンロードをスキップしています。",
        "log_selected_format": "選択されたフォーマット: {}",
        "log_starting_media_download": "メディアファイルと字幕のダウンロードを開始しています...",
        "log_media_download_complete": "メディアファイルのダウンロードが完了しました: {}",
        "warning_media_file_not_found": "ダウンロードされたメディアファイルが見つかりませんでした。",
        "log_skipped_media_download": "メディアファイルのダウンロードをスキップしました。",
        "log_front_sub_download_complete": "表面の字幕ファイルのダウンロードが完了しました: {}",
        "warning_front_sub_not_found": "表面の字幕ファイル ({}) が見つかりませんでした。",
        "log_back_sub_download_complete": "裏面の字幕ファイルのダウンロードが完了しました: {}",
        "warning_back_sub_not_found": "裏面の字幕ファイル ({}) が見つかりませんでした。",
        "title_download_complete": "ダウンロード完了",
        "log_download_finished_processing": "ダウンロードが完了し、処理中です...",
        "error_downloading": "ダウンロード中にエラーが発生しました: {}",
        "log_download_complete_log": "ダウンロード完了",
        "prompt_autofill": "ダウンロード完了。「Ankiパッケージを生成」タブにファイルパスを自動入力しますか？",
        "error_detecting_lang": "言語の検出中にエラーが発生しました: {}",
        "error_parsing_srt": "字幕ファイルの解析中にエラーが発生しました: {}",
        "error_invalid_time_format": "無効な時間形式: {}",
        "log_applying_start_time": "開始時間を適用しています: {} ({}ms)",
        "log_applying_end_time": "終了時間を適用しています: {} ({}ms)",
        "warning_edge_tts_no_slow": "edge-ttsは低速音声をサポートしていないため、通常の速度で生成します。",
        "error_unknown_tts_engine": "不明なTTSエンジン: {}",
        "error_generating_tts": "'{}'でのTTS生成中にエラーが発生しました: {}",
        "warning_tts_fallback": "TTSエンジン'{}'が失敗しました。フォールバックエンジン'{}'を試しています...",
        "log_tts_fallback_success": "フォールバックTTSエンジン'{}'が成功しました。",
        "error_extracting_audio": "音声セグメントの抽出中にエラーが発生しました: {}",
        "warning_add_furigana": "ふりがなの追加中にエラーが発生しました: '{}'。エラー: {}",
        "warning_add_pinyin": "ピンインの追加中にエラーが発生しました: '{}'。エラー: {}",
        "warning_add_romanization_ko": "韓国語のローマ字表記の追加中にエラーが発生しました: '{}'。エラー: {}",
        "error_preview_need_subs": "プレビューのために表面と裏面の字幕ファイルを選択してください。",
        "error_preview_need_output_dir": "プレビューファイルを保存する出力ディレクトリを選択してください。",
        "log_preview_generating": "プレビューを生成しています...",
        "log_merging_front_subs": "表面の字幕をマージしています、最大ギャップ: {}ms",
        "log_merging_back_subs": "裏面の字幕をマージしています、最大ギャップ: {}ms",
        "error_preview_no_subs": "字幕ファイルの解析に失敗したか、時間範囲内に字幕がないため、プレビューできません。",
        "error_init_pykakasi": "pykakasiの初期化に失敗しました: {}",
        "warning_no_subs_for_preview": "プレビューを生成するための十分な字幕データがありません。",
        "log_processing_preview_cards": "プレビュー用に最初の{}枚のカードを処理しています...",
        "log_preview_opened": "プレビューがブラウザで開かれました。ファイルは次の場所に保存されています: {}",
        "error_generating_preview": "プレビューの生成中にエラーが発生しました: {}",
        "preview_audio_placeholder_front": "[表面の音声はここに表示されます]",
        "preview_audio_placeholder_back": "[裏面の音声はここに表示されます]",
        "preview_card_title": "カード {}",
        "preview_card_front": "表面",
        "preview_card_back": "裏面",
        "error_need_front_sub": "表面の字幕ファイルを選択してください",
        "error_need_back_sub": "裏面の字幕ファイルを選択してください",
        "error_need_csv_file": "CSVファイルを選択してください",
        "error_need_output_dir": "出力ディレクトリを選択してください",
        "error_need_package_name": "Ankiパッケージ名を入力してください",
        "error_invalid_offset": "タイムラインオフセットは有効な整数でなければなりません。",
        "log_anki_generating": "Ankiパッケージを生成しています...",
        "log_anki_generating_from_csv": "CSVからAnkiパッケージを生成しています...",
        "log_timeline_offset": "タイムラインオフセットを適用しています: {} ms",
        "error_anki_pkg_exists": "Ankiパッケージ'{}'は既に存在します。「既存のAnkiパッケージを上書き」をチェックするか、パッケージ名を変更してください。",
        "log_loading_media": "メディアファイルをメモリに読み込んでいます: {}",
        "log_media_loaded": "メディアファイルが読み込まれました。",
        "error_loading_media": "メディアファイルの読み込みに失敗しました: {}",
        "error_parsing_subs_or_empty": "字幕ファイルの解析に失敗したか、時間範囲内に字幕がありません",
        "log_detected_front_lang": "表面の字幕言語を検出しました: {}",
        "log_detected_back_lang": "裏面の字幕言語を検出しました: {}",
        "log_ja_detected_init_kakasi": "日本語の字幕が検出されました、ルビ文字ツールを初期化しています...",
        "log_kakasi_initialized": "ルビ文字ツールが初期化されました。",
        "error_init_kakasi": "ルビ文字ツール(pykakasi)の初期化に失敗しました: {}",
        "log_zh_detected_add_pinyin": "中国語の字幕が検出されました、ピンインを追加します。",
        "log_ko_detected_add_romanization": "韓国語の字幕が検出されました、ローマ字表記を追加します。",
        "log_generation_progress": "生成進捗: {:.1f}%",
        "warning_extract_audio_failed_tts_fallback": "メディアファイルからの音声抽出に失敗しました、裏面の音声にTTSフォールバックを使用します: {}",
        "log_generating_anki_pkg": "Ankiパッケージを生成しています...",
        "anki_model_name": "バイリンガル学習カード",
        "anki_card_name": "カード1",
        "log_anki_pkg_complete": "Ankiパッケージの生成が完了しました: {}",
        "error_generating_anki_pkg": "Ankiパッケージの生成中にエラーが発生しました: {}",
        "log_cleaning_temp_files": "一時ファイルをクリーンアップしています...",
        "log_cleaned_mp3": "一時.mp3ファイルがクリーンアップされました。",
        "log_cleaned_csv": "一時.csvファイルがクリーンアップされました。",
        "error_cleaning_temp_files": "一時ファイルのクリーンアップ中にエラーが発生しました: {}",
        "log_config_loaded": "設定が読み込まれました",
        "error_loading_config": "設定の読み込み中にエラーが発生しました: {}",
        "log_deleted_preview_file": "プレビューファイルを削除しました: {}",
        "error_deleting_preview_file": "プレビューファイルの削除中にエラーが発生しました: {}",
        "label_language": "言語:",
        "label_screenshot_options": "スクリーンショットオプション:",
        "check_add_screenshot": "スクリーンショットを追加",
        "label_screenshot_timestamp": "タイムスタンプ:",
        "label_screenshot_quality": "品質 (1-31):",
        "check_cleanup_jpg": ".jpgファイルをクリーンアップ",
        "check_cleanup_preview_html": "プレビューHTMLファイルをクリーンアップ",
        "log_cleaned_preview_html": "一時的なプレビューHTMLファイルがクリーンアップされました: {}",
        "error_ffmpeg_not_found": "FFmpegが見つかりません。FFmpegがインストールされ、システムのPATHに追加されていることを確認してください。",
        "error_taking_screenshot": "スクリーンショットの撮影中にエラーが発生しました: {}",
        "log_screenshot_taken": "{}sでスクリーンショットを撮影し、{} に保存しました",
        "log_cleaned_jpg": "一時的な.jpgファイルがクリーンアップされました。",
        "preview_screenshot_placeholder": "[スクリーンショットはここに表示されます]",
        "screenshot_time_start": "開始",
        "screenshot_time_middle": "中間",
        "screenshot_time_end": "終了",
        "warning_same_subtitle_language": "表面と裏面の字幕言語は同じにできません。裏面の言語は自動的に調整されました。",
        "error_no_alternative_language": "裏面の字幕の代替言語が見つかりませんでした。手動で異なる言語を選択してください。",
        "error_config_corrupted": "エラー：config.jsonが破損しています。デフォルト設定を使用します。",
        "config_saved_restart": "設定が保存されました。すべての変更を有効にするには、アプリケーションを再起動してください。",
        "welcome_title": "初期設定",
        "welcome_message": "ようこそ！開始するには、ご希望の表示言語とAnkiカードの表面・裏面のデフォルト言語を選択してください。",
        "select_front_lang": "デフォルトの表面言語を選択：",
        "select_back_lang": "デフォルトの裏面言語を選択：",
        "error_select_both_langs": "続行するには、表面と裏面の両方の言語を選択してください。",
        "error_internal_lang_map": "内部エラー：選択した言語の表示名をコードにマッピングできませんでした。",
        "button_continue": "続行",
        "button_cancel": "キャンセル",
        "label_help": "ヘルプ",
        "check_dont_validate_url": "URLを検証しない",
        "log_url_validation_changed": "URLの検証が{}されました",
        "tooltip_dont_validate_url_check": "デフォルトでは、https://www.youtube.com/watch?v=... のような単一のYouTubeダウンロードリンクのみがサポートされています。より多くのyt-dlpダウンロードサイトをサポートしたい場合は、これをチェックしてURLのチェックを強制的に無効にすることができます。",
        "tooltip_label_media_file": "この項目が空の場合、対応するファイルは分割されません"
    },
    "ko": {
        "app_title": "Anki 패키지 생성기",
        "tab_download": "오디오/비디오 및 자막 다운로드",
        "CSV_generate": "CSV로 카드 생성",
        "tab_generate": "Anki 패키지 생성",
        "tab_csv": "CSV",
        "tab_config": "설정",
        "label_progress": "진행률:",
        "label_log": "로그",
        "log_app_started": "애플리케이션이 시작되었습니다",
        "label_video_url": "비디오 URL:",
        "button_query_language": "언어 쿼리",
        "label_download_dir": "다운로드 디렉토리:",
        "button_browse": "찾아보기...",
        "label_av_format": "오디오/비디오 형식:",
        "label_front_sub_lang": "앞면 자막 언어:",
        "label_back_sub_lang": "뒷면 자막 언어:",
        "check_download_only_subs": "자막만 다운로드",
        "select_display_language": "표시 언어 선택:",
        "button_start_download": "다운로드 시작",
        "label_media_file": "미디어 파일 (선택 사항):",
        "label_front_sub_file": "앞면 자막 파일:",
        "label_back_sub_file": "뒷면 자막 파일:",
        "label_csv_file": "CSV 파일:",
        "label_output_dir": "출력 디렉토리:",
        "label_anki_package_name": "Anki 패키지 이름:",
        "label_tts_engine": "TTS 엔진:",
        "label_slow_speech": "느린 음성 (gTTS):",
        "check_slow_front": "앞면 느리게",
        "check_slow_back": "뒷면 느리게",
        "label_subtitle_cleanup": "자막 정리:",
        "check_remove_non_dialogue": "[음악], (박수) 등 비대화 내용 제거",
        "label_ruby_char_options": "루비 문자 옵션:",
        "check_add_ruby_front": "앞면에 추가",
        "check_add_ruby_back": "뒷면에 추가",
        "label_post_processing": "후처리:",
        "check_cleanup_mp3": ".mp3 파일 정리",
        "check_cleanup_csv": ".csv 파일 정리",
        "label_timeline_offset": "타임라인 오프셋 (ms):",
        "label_subtitle_time_range": "자막 시간 범위:",
        "label_start_time": "시작 (HH:MM:SS):",
        "label_end_time": "종료 (HH:MM:SS):",
        "label_empty_for_end": "(끝까지 비워두기)",
        "label_subtitle_merge": "자막 병합:",
        "tooltip_merge_warning": "주의해서 사용하세요: 시간이 매우 가까운 자막 라인을 병합합니다.\n이로 인해 앞면과 뒷면 자막이 어긋나거나 오디오 타이밍이 부정확해질 수 있습니다.",
        "check_merge_subtitles": "가까운 자막 라인 병합",
        "label_max_merge_gap": "최대 간격 (ms):",
        "label_file_handling": "파일 처리:",
        "check_overwrite_anki": "기존 Anki 패키지 덮어쓰기",
        "button_preview": "처음 5개 카드 미리보기",
        "button_generate": "Anki 패키지 생성",
        "label_default_front_lang": "기본 앞면 자막 언어:",
        "label_default_back_lang": "기본 뒷면 자막 언어:",
        "label_anki_template_style": "Anki 템플릿 및 스타일:",
        "tab_front_template": "앞면 템플릿",
        "tab_back_template": "뒷면 템플릿",
        "tab_stylesheet": "스타일시트",
        "tab_preview_html_template": "미리보기 HTML 템플릿",
        "button_restore_config": "기본값으로 복원",
        "button_save_config": "설정 저장",
        "log_config_updated": "UI에 설정이 업데이트되었습니다",
        "log_config_restored": "설정이 복원되었습니다",
        "log_config_saved": "설정이 저장되었습니다",
        "error_saving_config": "설정 저장 중 오류 발생: {}",
        "log_url_from_clipboard": "클립보드에서 URL 감지: {}",
        "error_checking_clipboard": "클립보드 확인 중 오류 발생: {}",
        "error_enter_video_url": "비디오 URL을 입력하세요",
        "error_enter_valid_url": "유효한 URL을 입력하세요",
        "log_querying_video_info": "비디오 정보 쿼리 중: {}",
        "error_querying_video_info": "비디오 정보 쿼리 중 오류 발생: {}",
        "log_query_complete": "쿼리 완료. {}개의 형식과 {}개의 자막을 찾았습니다.",
        "error_playlist_not_supported": "재생 목록 URL은 지원되지 않습니다. 단일 비디오 URL을 입력하십시오.",
        "filetype_media_files": "미디어 파일",
        "filetype_csv_files": "CSV 파일",
        "log_auto_set_output_dir": "출력 디렉토리를 자동으로 설정했습니다: {}",
        "log_auto_set_package_name": "Anki 패키지 이름을 자동으로 설정했습니다: {}",
        "filetype_subtitle_files": "자막 파일",
        "log_auto_set_output_dir_from_sub": "자막 파일을 기반으로 출력 디렉토리를 자동으로 설정했습니다: {}",
        "log_trying_auto_match_subs": "미디어 파일에 대한 자막 자동 일치 시도 중: {}",
        "log_no_default_lang_for_match": "설정에 기본 자막 언어가 설정되지 않아 자동 일치를 건너뜁니다.",
        "log_auto_matched_front_sub": "앞면 자막 파일 자동 일치 ({}): {}",
        "log_auto_matched_back_sub": "뒷면 자막 파일 자동 일치 ({}): {}",
        "error_select_download_dir": "다운로드 디렉토리를 선택하세요",
        "log_created_download_dir": "다운로드 디렉토리를 생성했습니다: {}",
        "error_creating_download_dir": "다운로드 디렉토리 생성 중 오류 발생: {}",
        "error_select_av_format": "오디오/비디오 형식을 선택하세요",
        "error_select_sub_lang": "자막 언어를 선택하세요",
        "log_processing_started": "처리 시작: {}",
        "log_download_dir": "다운로드 디렉토리: {}",
        "log_front_sub_lang": "앞면 자막 언어: {}",
        "log_back_sub_lang": "뒷면 자막 언어: {}",
        "log_skip_media_download": "요청에 따라 미디어 파일 다운로드를 건너뜁니다.",
        "log_selected_format": "선택된 형식: {}",
        "log_starting_media_download": "미디어 파일 및 자막 다운로드 시작 중...",
        "log_media_download_complete": "미디어 파일 다운로드 완료: {}",
        "warning_media_file_not_found": "다운로드한 미디어 파일을 찾을 수 없습니다.",
        "log_skipped_media_download": "미디어 파일 다운로드를 건너뛰었습니다.",
        "log_front_sub_download_complete": "앞면 자막 파일 다운로드 완료: {}",
        "warning_front_sub_not_found": "앞면 자막 파일({})을 찾을 수 없습니다.",
        "log_back_sub_download_complete": "뒷면 자막 파일 다운로드 완료: {}",
        "warning_back_sub_not_found": "뒷면 자막 파일({})을 찾을 수 없습니다.",
        "title_download_complete": "다운로드 완료",
        "log_download_finished_processing": "다운로드 완료, 처리 중...",
        "error_downloading": "다운로드 중 오류 발생: {}",
        "log_download_complete_log": "다운로드 완료",
        "prompt_autofill": "다운로드 완료. 'Anki 패키지 생성' 탭에 파일 경로를 자동 완성하시겠습니까?",
        "error_detecting_lang": "언어 감지 중 오류 발생: {}",
        "error_parsing_srt": "자막 파일 구문 분석 중 오류 발생: {}",
        "error_invalid_time_format": "잘못된 시간 형식: {}",
        "log_applying_start_time": "시작 시간 적용 중: {} ({}ms)",
        "log_applying_end_time": "종료 시간 적용 중: {} ({}ms)",
        "warning_edge_tts_no_slow": "edge-tts는 느린 음성을 지원하지 않으므로 일반 속도로 생성합니다.",
        "error_unknown_tts_engine": "알 수 없는 TTS 엔진: {}",
        "error_generating_tts": "'{}'로 TTS 생성 중 오류 발생: {}",
        "warning_tts_fallback": "TTS 엔진 '{}' 실패. 대체 엔진 '{}' 시도 중...",
        "log_tts_fallback_success": "대체 TTS 엔진 '{}' 성공.",
        "error_extracting_audio": "오디오 세그먼트 추출 중 오류 발생: {}",
        "warning_add_furigana": "후리가나 추가 중 오류 발생: '{}'. 오류: {}",
        "warning_add_pinyin": "병음 추가 중 오류 발생: '{}'. 오류: {}",
        "warning_add_romanization_ko": "한국어 로마자 표기 추가 중 오류 발생: '{}'. 오류: {}",
        "error_preview_need_subs": "미리보기를 위해 앞면 및 뒷면 자막 파일을 선택하세요.",
        "error_preview_need_output_dir": "미리보기 파일을 저장할 출력 디렉토리를 선택하세요.",
        "log_preview_generating": "미리보기 생성 중...",
        "log_merging_front_subs": "앞면 자막 병합 중, 최대 간격: {}ms",
        "log_merging_back_subs": "뒷면 자막 병합 중, 최대 간격: {}ms",
        "error_preview_no_subs": "자막 파일을 구문 분석하지 못했거나 시간 범위에 자막이 없어 미리볼 수 없습니다.",
        "error_init_pykakasi": "pykakasi 초기화 실패: {}",
        "warning_no_subs_for_preview": "미리보기를 생성할 자막 데이터가 충분하지 않습니다.",
        "log_processing_preview_cards": "미리보기를 위해 처음 {}개 카드 처리 중...",
        "log_preview_opened": "브라우저에서 미리보기가 열렸습니다. 파일 저장 위치: {}",
        "error_generating_preview": "미리보기 생성 중 오류 발생: {}",
        "preview_audio_placeholder_front": "[앞면 오디오가 여기에 표시됩니다]",
        "preview_audio_placeholder_back": "[뒷면 오디오가 여기에 표시됩니다]",
        "preview_card_title": "카드 {}",
        "preview_card_front": "앞면",
        "preview_card_back": "뒷면",
        "error_need_front_sub": "앞면 자막 파일을 선택하세요",
        "error_need_back_sub": "뒷면 자막 파일을 선택하세요",
        "error_need_csv_file": "CSV 파일을 선택하세요",
        "error_need_output_dir": "출력 디렉토리를 선택하세요",
        "error_need_package_name": "Anki 패키지 이름을 입력하세요",
        "error_invalid_offset": "타임라인 오프셋은 유효한 정수여야 합니다.",
        "log_anki_generating": "Anki 패키지 생성 중...",
        "log_anki_generating_from_csv": "CSV에서 Anki 패키지를 생성하는 중...",
        "log_timeline_offset": "타임라인 오프셋 적용 중: {} ms",
        "error_anki_pkg_exists": "Anki 패키지 '{}'가 이미 존재합니다. '기존 Anki 패키지 덮어쓰기'를 선택하거나 패키지 이름을 변경하세요.",
        "log_loading_media": "미디어 파일을 메모리로 로드 중: {}",
        "log_media_loaded": "미디어 파일이 로드되었습니다.",
        "error_loading_media": "미디어 파일 로드 실패: {}",
        "error_parsing_subs_or_empty": "자막 파일을 구문 분석하지 못했거나 시간 범위에 자막이 없습니다",
        "log_detected_front_lang": "앞면 자막 언어 감지: {}",
        "log_detected_back_lang": "뒷면 자막 언어 감지: {}",
        "log_ja_detected_init_kakasi": "일본어 자막 감지, 루비 문자 도구 초기화 중...",
        "log_kakasi_initialized": "루비 문자 도구가 초기화되었습니다.",
        "error_init_kakasi": "루비 문자 도구(pykakasi) 초기화 실패: {}",
        "log_zh_detected_add_pinyin": "중국어 자막 감지, 병음을 추가합니다.",
        "log_ko_detected_add_romanization": "한국어 자막 감지, 로마자 표기를 추가합니다.",
        "log_generation_progress": "생성 진행률: {:.1f}%",
        "warning_extract_audio_failed_tts_fallback": "미디어 파일에서 오디오 추출 실패, 뒷면 오디오에 TTS 대체 사용: {}",
        "log_generating_anki_pkg": "Anki 패키지 생성 중...",
        "anki_model_name": "이중 언어 학습 카드",
        "anki_card_name": "카드 1",
        "log_anki_pkg_complete": "Anki 패키지 생성 완료: {}",
        "error_generating_anki_pkg": "Anki 패키지 생성 중 오류 발생: {}",
        "log_cleaning_temp_files": "임시 파일 정리 중...",
        "log_cleaned_mp3": "임시 .mp3 파일이 정리되었습니다.",
        "log_cleaned_csv": "임시 .csv 파일이 정리되었습니다.",
        "error_cleaning_temp_files": "임시 파일 정리 중 오류 발생: {}",
        "log_config_loaded": "설정이 로드되었습니다",
        "error_loading_config": "설정 로드 중 오류 발생: {}",
        "log_deleted_preview_file": "미리보기 파일을 삭제했습니다: {}",
        "error_deleting_preview_file": "미리보기 파일 삭제 중 오류 발생: {}",
        "label_language": "언어:",
        "label_screenshot_options": "스크린샷 옵션:",
        "check_add_screenshot": "스크린샷 추가",
        "label_screenshot_timestamp": "타임스탬프:",
        "label_screenshot_quality": "품질 (1-31):",
        "check_cleanup_jpg": ".jpg 파일 정리",
        "check_cleanup_preview_html": "미리보기 HTML 파일 정리",
        "log_cleaned_preview_html": "임시 미리보기 HTML 파일이 정리되었습니다: {}",
        "error_ffmpeg_not_found": "FFmpeg을 찾을 수 없습니다. FFmpeg이 설치되어 있고 시스템 PATH에 추가되었는지 확인하십시오.",
        "error_taking_screenshot": "스크린샷 촬영 중 오류 발생: {}",
        "log_screenshot_taken": "{}초에 스크린샷을 촬영하여 {}에 저장했습니다",
        "log_cleaned_jpg": "임시 .jpg 파일이 정리되었습니다.",
        "preview_screenshot_placeholder": "[스크린샷이 여기에 표시됩니다]",
        "screenshot_time_start": "시작",
        "screenshot_time_middle": "중간",
        "screenshot_time_end": "끝",
        "warning_same_subtitle_language": "앞면과 뒷면 자막 언어는 같을 수 없습니다. 뒷면 언어가 자동으로 조정되었습니다。",
        "error_no_alternative_language": "뒷면 자막에 대한 대체 언어를 찾을 수 없습니다. 다른 언어를 수동으로 선택하십시오.",
        "error_config_corrupted": "오류: config.json이 손상되었습니다. 기본 설정을 사용합니다.",
        "config_saved_restart": "구성이 저장되었습니다. 모든 변경 사항을 적용하려면 응용 프로그램을 다시 시작하십시오.",
        "welcome_title": "초기 설정",
        "welcome_message": "환영합니다! 시작하려면 선호하는 표시 언어와 Anki 카드의 앞면 및 뒷면 기본 언어를 선택하십시오.",
        "select_front_lang": "기본 앞면 언어 선택:",
        "select_back_lang": "기본 뒷면 언어 선택:",
        "error_select_both_langs": "계속하려면 앞면과 뒷면 언어를 모두 선택하십시오.",
        "error_internal_lang_map": "내부 오류: 선택한 언어 표시 이름을 코드로 매핑할 수 없습니다.",
        "button_continue": "계속",
        "button_cancel": "취소",
        "label_help": "도움말",
        "check_dont_validate_url": "URL 유효성 검사 안 함",
        "log_url_validation_changed": "URL 유효성 검사가 {}되었습니다",
        "tooltip_dont_validate_url_check": "기본적으로 https://www.youtube.com/watch?v=... 와 같은 단일 YouTube 다운로드 링크만 지원됩니다. 더 많은 yt-dlp 다운로드 사이트를 지원하려면 이 항목을 선택하여 URL 검사를 강제로 비활성화할 수 있습니다。",
        "tooltip_label_media_file": "이 항목이 비어 있으면 해당 파일이 분할되지 않음을 의미합니다"
    },
    "vi": {
        "app_title": "Trình tạo gói Anki",
        "tab_download": "Tải xuống Âm thanh/Video và Phụ đề",
        "CSV_generate": "Tạo thẻ từ CSV",
        "tab_generate": "Tạo gói Anki",
        "tab_csv": "CSV",
        "tab_config": "Cấu hình",
        "label_progress": "Tiến trình:",
        "label_log": "Nhật ký",
        "log_app_started": "Ứng dụng đã khởi động",
        "label_video_url": "URL Video:",
        "button_query_language": "Truy vấn ngôn ngữ",
        "label_download_dir": "Thư mục tải xuống:",
        "button_browse": "Duyệt...",
        "label_av_format": "Định dạng Âm thanh/Video:",
        "label_front_sub_lang": "Ngôn ngữ phụ đề mặt trước:",
        "label_back_sub_lang": "Ngôn ngữ phụ đề mặt sau:",
        "check_download_only_subs": "Chỉ tải xuống phụ đề",
        "select_display_language": "Chọn ngôn ngữ hiển thị:",
        "button_start_download": "Bắt đầu tải xuống",
        "label_media_file": "Tệp phương tiện (Tùy chọn):",
        "label_front_sub_file": "Tệp phụ đề mặt trước:",
        "label_back_sub_file": "Tệp phụ đề mặt sau:",
        "label_csv_file": "Tệp CSV:",
        "label_output_dir": "Thư mục đầu ra:",
        "label_anki_package_name": "Tên gói Anki:",
        "label_tts_engine": "Công cụ TTS:",
        "label_slow_speech": "Phát âm chậm (gTTS):",
        "check_slow_front": "Mặt trước chậm",
        "check_slow_back": "Mặt sau chậm",
        "label_subtitle_cleanup": "Dọn dẹp phụ đề:",
        "check_remove_non_dialogue": "Xóa các phần không phải hội thoại như [Nhạc], (Vỗ tay)",
        "label_ruby_char_options": "Tùy chọn ký tự Ruby:",
        "check_add_ruby_front": "Thêm vào mặt trước",
        "check_add_ruby_back": "Thêm vào mặt sau",
        "label_post_processing": "Xử lý hậu kỳ:",
        "check_cleanup_mp3": "Dọn dẹp tệp .mp3",
        "check_cleanup_csv": "Dọn dẹp tệp .csv",
        "label_timeline_offset": "Độ lệch dòng thời gian (ms):",
        "label_subtitle_time_range": "Phạm vi thời gian phụ đề:",
        "label_start_time": "Bắt đầu (HH:MM:SS):",
        "label_end_time": "Kết thúc (HH:MM:SS):",
        "label_empty_for_end": "(trống để kết thúc)",
        "label_subtitle_merge": "Gộp phụ đề:",
        "tooltip_merge_warning": "Sử dụng cẩn thận: Gộp các dòng phụ đề có thời gian rất gần nhau.\nĐiều này có thể gây lệch giữa phụ đề mặt trước và mặt sau hoặc thời gian âm thanh không chính xác.",
        "check_merge_subtitles": "Gộp các dòng phụ đề gần nhau",
        "label_max_merge_gap": "Khoảng cách tối đa (ms):",
        "label_file_handling": "Xử lý tệp:",
        "check_overwrite_anki": "Ghi đè gói Anki hiện có",
        "button_preview": "Xem trước 5 thẻ đầu tiên",
        "button_generate": "Tạo gói Anki",
        "label_default_front_lang": "Ngôn ngữ phụ đề mặt trước mặc định:",
        "label_default_back_lang": "Ngôn ngữ phụ đề mặt sau mặc định:",
        "label_anki_template_style": "Mẫu và Kiểu dáng Anki:",
        "tab_front_template": "Mẫu mặt trước",
        "tab_back_template": "Mẫu mặt sau",
        "tab_stylesheet": "Bảng định kiểu",
        "tab_preview_html_template": "Mẫu HTML xem trước",
        "button_restore_config": "Khôi phục mặc định",
        "button_save_config": "Lưu cấu hình",
        "log_config_updated": "Cấu hình đã được cập nhật trong giao diện người dùng",
        "log_config_restored": "Cấu hình đã được khôi phục",
        "log_config_saved": "Cấu hình đã được lưu",
        "error_saving_config": "Lỗi khi lưu cấu hình: {}",
        "log_url_from_clipboard": "Đã phát hiện URL từ khay nhớ tạm: {}",
        "error_checking_clipboard": "Lỗi khi kiểm tra khay nhớ tạm: {}",
        "error_enter_video_url": "Vui lòng nhập URL video",
        "error_enter_valid_url": "Vui lòng nhập URL hợp lệ",
        "log_querying_video_info": "Đang truy vấn thông tin video: {}",
        "error_querying_video_info": "Lỗi khi truy vấn thông tin video: {}",
        "log_query_complete": "Truy vấn hoàn tất. Tìm thấy {} định dạng và {} phụ đề.",
        "error_playlist_not_supported": "URL danh sách phát không được hỗ trợ. Vui lòng cung cấp URL của một video duy nhất.",
        "filetype_media_files": "Tệp phương tiện",
        "filetype_csv_files": "Tệp CSV",
        "log_auto_set_output_dir": "Đã tự động đặt thư mục đầu ra thành: {}",
        "log_auto_set_package_name": "Đã tự động đặt tên gói Anki thành: {}",
        "filetype_subtitle_files": "Tệp phụ đề",
        "log_auto_set_output_dir_from_sub": "Đã tự động đặt thư mục đầu ra dựa trên tệp phụ đề: {}",
        "log_trying_auto_match_subs": "Đang cố gắng tự động khớp phụ đề cho tệp phương tiện: {}",
        "log_no_default_lang_for_match": "Ngôn ngữ phụ đề mặc định không được đặt trong cấu hình, bỏ qua tự động khớp.",
        "log_auto_matched_front_sub": "Đã tự động khớp tệp phụ đề mặt trước ({}): {}",
        "log_auto_matched_back_sub": "Đã tự động khớp tệp phụ đề mặt sau ({}): {}",
        "error_select_download_dir": "Vui lòng chọn thư mục tải xuống",
        "log_created_download_dir": "Đã tạo thư mục tải xuống: {}",
        "error_creating_download_dir": "Lỗi khi tạo thư mục tải xuống: {}",
        "error_select_av_format": "Vui lòng chọn định dạng âm thanh/video",
        "error_select_sub_lang": "Vui lòng chọn ngôn ngữ phụ đề",
        "log_processing_started": "Bắt đầu xử lý: {}",
        "log_download_dir": "Thư mục tải xuống: {}",
        "log_front_sub_lang": "Ngôn ngữ phụ đề mặt trước: {}",
        "log_back_sub_lang": "Ngôn ngữ phụ đề mặt sau: {}",
        "log_skip_media_download": "Bỏ qua tải xuống tệp phương tiện theo yêu cầu.",
        "log_selected_format": "Định dạng đã chọn: {}",
        "log_starting_media_download": "Bắt đầu tải xuống tệp phương tiện và phụ đề...",
        "log_media_download_complete": "Tải xuống tệp phương tiện hoàn tất: {}",
        "warning_media_file_not_found": "Không thể tìm thấy tệp phương tiện đã tải xuống.",
        "log_skipped_media_download": "Đã bỏ qua tải xuống tệp phương tiện.",
        "log_front_sub_download_complete": "Tải xuống tệp phụ đề mặt trước hoàn tất: {}",
        "warning_front_sub_not_found": "Không thể tìm thấy tệp phụ đề mặt trước ({}).",
        "log_back_sub_download_complete": "Tải xuống tệp phụ đề mặt sau hoàn tất: {}",
        "warning_back_sub_not_found": "Không thể tìm thấy tệp phụ đề mặt sau ({}).",
        "title_download_complete": "Tải xuống hoàn tất",
        "log_download_finished_processing": "Tải xuống hoàn tất, đang xử lý...",
        "error_downloading": "Lỗi trong quá trình tải xuống: {}",
        "log_download_complete_log": "Tải xuống hoàn tất",
        "prompt_autofill": "Tải xuống hoàn tất. Tự động điền đường dẫn tệp vào tab 'Tạo gói Anki'?",
        "error_detecting_lang": "Lỗi khi phát hiện ngôn ngữ: {}",
        "error_parsing_srt": "Lỗi khi phân tích cú pháp tệp phụ đề: {}",
        "error_invalid_time_format": "Định dạng thời gian không hợp lệ: {}",
        "log_applying_start_time": "Đang áp dụng thời gian bắt đầu: {} ({}ms)",
        "log_applying_end_time": "Đang áp dụng thời gian kết thúc: {} ({}ms)",
        "warning_edge_tts_no_slow": "edge-tts không hỗ trợ phát âm chậm, đang tạo ở tốc độ bình thường.",
        "error_unknown_tts_engine": "Công cụ TTS không xác định: {}",
        "error_generating_tts": "Lỗi khi tạo TTS với '{}': {}",
        "warning_tts_fallback": "Công cụ TTS '{}' không thành công. Đang thử công cụ dự phòng '{}'...",
        "log_tts_fallback_success": "Công cụ TTS dự phòng '{}' đã thành công.",
        "error_extracting_audio": "Lỗi khi trích xuất đoạn âm thanh: {}",
        "warning_add_furigana": "Lỗi khi thêm furigana: '{}'. Lỗi: {}",
        "warning_add_pinyin": "Lỗi khi thêm pinyin: '{}'. Lỗi: {}",
        "warning_add_romanization_ko": "Lỗi khi thêm chữ La tinh tiếng Hàn: '{}'. Lỗi: {}",
        "error_preview_need_subs": "Vui lòng chọn tệp phụ đề mặt trước và mặt sau để xem trước.",
        "error_preview_need_output_dir": "Vui lòng chọn thư mục đầu ra để lưu tệp xem trước.",
        "log_preview_generating": "Đang tạo bản xem trước...",
        "log_merging_front_subs": "Đang gộp phụ đề mặt trước, khoảng cách tối đa: {}ms",
        "log_merging_back_subs": "Đang gộp phụ đề mặt sau, khoảng cách tối đa: {}ms",
        "error_preview_no_subs": "Không thể phân tích cú pháp tệp phụ đề hoặc không có phụ đề trong phạm vi thời gian, không thể xem trước.",
        "error_init_pykakasi": "Không thể khởi tạo pykakasi: {}",
        "warning_no_subs_for_preview": "Không đủ dữ liệu phụ đề để tạo bản xem trước.",
        "log_processing_preview_cards": "Đang xử lý {} thẻ đầu tiên để xem trước...",
        "log_preview_opened": "Bản xem trước đã được mở trong trình duyệt. Tệp được lưu tại: {}",
        "error_generating_preview": "Lỗi khi tạo bản xem trước: {}",
        "preview_audio_placeholder_front": "[Âm thanh mặt trước sẽ ở đây]",
        "preview_audio_placeholder_back": "[Âm thanh mặt sau sẽ ở đây]",
        "preview_card_title": "Thẻ {}",
        "preview_card_front": "Mặt trước",
        "preview_card_back": "Mặt sau",
        "error_need_front_sub": "Vui lòng chọn tệp phụ đề mặt trước",
        "error_need_back_sub": "Vui lòng chọn tệp phụ đề mặt sau",
        "error_need_csv_file": "Vui lòng chọn tệp CSV",
        "error_need_output_dir": "Vui lòng chọn thư mục đầu ra",
        "error_need_package_name": "Vui lòng nhập tên gói Anki",
        "error_invalid_offset": "Độ lệch dòng thời gian phải là một số nguyên hợp lệ.",
        "log_anki_generating": "Đang tạo gói Anki...",
        "log_anki_generating_from_csv": "Đang tạo gói Anki từ CSV...",
        "log_timeline_offset": "Đang áp dụng độ lệch dòng thời gian: {} ms",
        "error_anki_pkg_exists": "Gói Anki '{}' đã tồn tại. Vui lòng chọn 'Ghi đè gói Anki hiện có' hoặc thay đổi tên gói.",
        "log_loading_media": "Đang tải tệp phương tiện vào bộ nhớ: {}",
        "log_media_loaded": "Tệp phương tiện đã được tải.",
        "error_loading_media": "Không thể tải tệp phương tiện: {}",
        "error_parsing_subs_or_empty": "Không thể phân tích cú pháp tệp phụ đề hoặc không có phụ đề trong phạm vi thời gian",
        "log_detected_front_lang": "Đã phát hiện ngôn ngữ phụ đề mặt trước: {}",
        "log_detected_back_lang": "Đã phát hiện ngôn ngữ phụ đề mặt sau: {}",
        "log_ja_detected_init_kakasi": "Đã phát hiện phụ đề tiếng Nhật, đang khởi tạo công cụ ký tự ruby...",
        "log_kakasi_initialized": "Công cụ ký tự ruby đã được khởi tạo.",
        "error_init_kakasi": "Không thể khởi tạo công cụ ký tự ruby (pykakasi): {}",
        "log_zh_detected_add_pinyin": "Đã phát hiện phụ đề tiếng Trung, sẽ thêm Pinyin.",
        "log_ko_detected_add_romanization": "Đã phát hiện phụ đề tiếng Hàn, sẽ thêm chữ La tinh.",
        "log_generation_progress": "Tiến trình tạo: {:.1f}%",
        "warning_extract_audio_failed_tts_fallback": "Không thể trích xuất âm thanh từ tệp phương tiện, chuyển sang TTS cho âm thanh mặt sau: {}",
        "log_generating_anki_pkg": "Đang tạo gói Anki...",
        "anki_model_name": "Thẻ học song ngữ",
        "anki_card_name": "Thẻ 1",
        "log_anki_pkg_complete": "Tạo gói Anki hoàn tất: {}",
        "error_generating_anki_pkg": "Lỗi khi tạo gói Anki: {}",
        "log_cleaning_temp_files": "Đang dọn dẹp các tệp tạm thời...",
        "log_cleaned_mp3": "Các tệp .mp3 tạm thời đã được dọn dẹp.",
        "log_cleaned_csv": "Tệp .csv tạm thời đã được dọn dẹp.",
        "error_cleaning_temp_files": "Lỗi khi dọn dẹp các tệp tạm thời: {}",
        "log_config_loaded": "Cấu hình đã được tải",
        "error_loading_config": "Lỗi khi tải cấu hình: {}",
        "log_deleted_preview_file": "Đã xóa tệp xem trước: {}",
        "error_deleting_preview_file": "Lỗi khi xóa tệp xem trước: {}",
        "label_language": "Ngôn ngữ:",
        "label_screenshot_options": "Tùy chọn ảnh chụp màn hình:",
        "check_add_screenshot": "Thêm ảnh chụp màn hình",
        "label_screenshot_timestamp": "Dấu thời gian:",
        "label_screenshot_quality": "Chất lượng (1-31):",
        "check_cleanup_jpg": "Dọn dẹp tệp .jpg",
        "check_cleanup_preview_html": "Dọn dẹp tệp HTML xem trước",
        "log_cleaned_preview_html": "Đã dọn dẹp tệp HTML xem trước tạm thời: {}",
        "error_ffmpeg_not_found": "Không tìm thấy FFmpeg. Vui lòng đảm bảo FFmpeg đã được cài đặt và thêm vào PATH của hệ thống.",
        "error_taking_screenshot": "Lỗi khi chụp ảnh màn hình: {}",
        "log_screenshot_taken": "Đã chụp ảnh màn hình lúc {}s, lưu vào {}",
        "log_cleaned_jpg": "Các tệp .jpg tạm thời đã được dọn dẹp.",
        "preview_screenshot_placeholder": "[Ảnh chụp màn hình sẽ ở đây]",
        "screenshot_time_start": "Bắt đầu",
        "screenshot_time_middle": "Giữa",
        "screenshot_time_end": "Kết thúc",
        "warning_same_subtitle_language": "Ngôn ngữ phụ đề mặt trước và mặt sau không được giống nhau. Ngôn ngữ mặt sau đã được tự động điều chỉnh。",
        "error_no_alternative_language": "Không tìm thấy ngôn ngữ thay thế cho phụ đề mặt sau. Vui lòng chọn các ngôn ngữ khác theo cách thủ công.",
        "error_config_corrupted": "Lỗi: config.json bị hỏng. Sử dụng cài đặt mặc định.",
        "config_saved_restart": "Cấu hình đã được lưu. Vui lòng khởi động lại ứng dụng để tất cả các thay đổi có hiệu lực.",
        "welcome_title": "Thiết lập ban đầu",
        "welcome_message": "Chào mừng! Để bắt đầu, vui lòng chọn ngôn ngữ hiển thị ưa thích của bạn và ngôn ngữ mặc định cho mặt trước và mặt sau của thẻ Anki.",
        "select_front_lang": "Chọn ngôn ngữ mặc định mặt trước:",
        "select_back_lang": "Chọn ngôn ngữ mặc định mặt sau:",
        "error_select_both_langs": "Vui lòng chọn cả ngôn ngữ mặt trước và mặt sau để tiếp tục.",
        "error_internal_lang_map": "Lỗi nội bộ: Không thể ánh xạ tên hiển thị ngôn ngữ đã chọn sang mã.",
        "button_continue": "Tiếp tục",
        "button_cancel": "Hủy",
        "label_help": "Trợ giúp",
        "check_dont_validate_url": "Không xác thực URL",
        "log_url_validation_changed": "Xác thực URL đã được {}",
        "tooltip_dont_validate_url_check": "Theo mặc định, chỉ hỗ trợ các liên kết tải xuống YouTube đơn lẻ như https://www.youtube.com/watch?v=.... Nếu bạn muốn hỗ trợ nhiều trang web tải xuống hơn từ yt-dlp, bạn có thể chọn mục này để buộc tắt kiểm tra URL.",
        "tooltip_label_media_file": "Nếu trường này trống, có nghĩa là tệp tương ứng sẽ không được phân đoạn"
    },
}

class Translator:
    def __init__(self, lang='zh'):
        self.lang = lang
        if self.lang not in STRINGS:
            self.lang = 'en' # Fallback to English

    def set_language(self, lang):
        if lang in STRINGS:
            self.lang = lang
        else:
            self.lang = 'en'

    def get_string(self, key, *args):
        string = STRINGS[self.lang].get(key, key)
        if args:
            return string.format(*args)
        return string

    def get_lang_display_name(self, lang_code):
        return f"{LANG_DISPLAY_NAMES[self.lang].get(lang_code.lower(), lang_code)} ({lang_code})"

# Global translator instance
translator = Translator()



def get_locale_string(key, *args):
    return translator.get_string(key, *args)

def set_language(lang):
    translator.set_language(lang)

def get_lang_display(lang_code):
    return translator.get_lang_display_name(lang_code)

def get_available_languages():
    return LANGUAGES

def get_available_display_languages():
    return LANG_DISPLAY_NAMES.get(translator.lang, LANG_DISPLAY_NAMES['en']);
